import './globals.css'
import { Footer, Navbar } from '@/components'
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    return (
      <html lang="en">
        <body>
          <div>
            <Navbar />
            {children}
            <Footer />
          </div>
        </body>
      </html>
    )
}
